# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvcl.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('limit_instances', models.IntegerField(default=0)),
                ('limit_cpus', models.IntegerField(default=0)),
                ('limit_ram', models.IntegerField(default=0, verbose_name='RAM limit in bytes')),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructs', to='cvcl.User')),
                ('users', models.ManyToManyField(to='cvcl.User')),
            ],
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('ip_address', models.GenericIPAddressField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvcl.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='VmDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_script', models.TextField()),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvcl.Flavor')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvcl.Image')),
            ],
        ),
        migrations.AddField(
            model_name='vm',
            name='vm_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvcl.VmDefinition'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_groups',
            field=models.ManyToManyField(to='cvcl.UserGroup'),
        ),
        migrations.AddField(
            model_name='environment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvcl.User'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='environment_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvcl.EnvironmentDefinition'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvcl.UserGroup'),
        ),
    ]
