# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0002_auto_20170310_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='vm',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
    ]
