# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 22:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0003_auto_20170310_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentdefinition',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentdefinition',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cvcl.EnvironmentDefinition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
