# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0006_auto_20170312_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
