# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0007_vm_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vm',
            old_name='state',
            new_name='status',
        ),
    ]
