# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0009_auto_20170315_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='environmentdefinition',
            options={'ordering': ['name'], 'verbose_name': 'Environment Definition'},
        ),
        migrations.AlterModelOptions(
            name='flavor',
            options={'ordering': ['ram']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='limit_cpus',
            new_name='limit_vcpus',
        ),
        migrations.AddField(
            model_name='image',
            name='min_disk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='min_ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Size in bytes'),
        ),
        migrations.AddField(
            model_name='user',
            name='limit_disk',
            field=models.IntegerField(default=0, verbose_name='Disk limit in GB'),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_disk',
            field=models.IntegerField(default=0, verbose_name='Disk usage in GB'),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_ram',
            field=models.IntegerField(default=0, verbose_name='RAM usage in GB'),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_vcpus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='disk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='swap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='vcpus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit_ram',
            field=models.IntegerField(default=0, verbose_name='RAM limit in GB'),
        ),
    ]
