# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0012_user_usage_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='disk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='ram',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='swap',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='vcpus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='min_disk',
            field=models.PositiveIntegerField(default=0, verbose_name='min ram in GB'),
        ),
        migrations.AlterField(
            model_name='image',
            name='min_ram',
            field=models.PositiveIntegerField(default=0, verbose_name='min ram in MB'),
        ),
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='size in bytes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit_disk',
            field=models.PositiveIntegerField(default=0, verbose_name='disk limit in GB'),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit_instances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit_ram',
            field=models.PositiveIntegerField(default=0, verbose_name='RAM limit in MB'),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit_vcpus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='usage_disk',
            field=models.PositiveIntegerField(default=0, verbose_name='disk usage in GB'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usage_instances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='usage_ram',
            field=models.PositiveIntegerField(default=0, verbose_name='RAM usage in MB'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usage_vcpus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
