# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0013_auto_20170315_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='min_disk',
            field=models.PositiveIntegerField(default=0, verbose_name='min disk in GB'),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit_instances',
            field=models.PositiveIntegerField(default=0, verbose_name='instance limit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit_vcpus',
            field=models.PositiveIntegerField(default=0, verbose_name='vCPUs limit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usage_instances',
            field=models.PositiveIntegerField(default=0, verbose_name='used instances'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usage_vcpus',
            field=models.PositiveIntegerField(default=0, verbose_name='vCPUs usage'),
        ),
    ]
