# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0014_auto_20170315_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='disk',
            field=models.PositiveIntegerField(default=0, verbose_name='disk size in GB'),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='ram',
            field=models.PositiveIntegerField(default=0, verbose_name='RAM size in MB'),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='swap',
            field=models.PositiveIntegerField(default=0, verbose_name='swap size in MB'),
        ),
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='size in bytes'),
        ),
        migrations.AlterField(
            model_name='vmdefinition',
            name='flavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvcl.Flavor'),
        ),
        migrations.AlterField(
            model_name='vmdefinition',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvcl.Image'),
        ),
    ]
