# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0015_auto_20170429_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOwnerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_owner_history', to='cvcl.Vm')),
            ],
            options={
                'verbose_name': 'IP Owner History',
            },
        ),
    ]
