# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0016_ipownerhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmdefinition',
            name='user_script',
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='hostname',
            field=models.CharField(blank=True, help_text='(Linux-only) When provided, will replace the hostname generated by default.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='powershell_script',
            field=models.TextField(blank=True, help_text='(Windows only) Run a Powershell script once when the instance is created.', null=True),
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='timezone',
            field=models.CharField(blank=True, help_text='(Linux-only) Example: America/New_York', max_length=50, null=True),
        ),
    ]
