# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0017_auto_20170429_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmdefinition',
            name='powershell_script',
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='shell_script',
            field=models.TextField(blank=True, help_text='Run a shell script when the instance is created. Must provide a shebang.', null=True),
        ),
    ]
