# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0019_auto_20170504_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmdefinition',
            old_name='public_key',
            new_name='default_user_public_key',
        ),
        migrations.RenameField(
            model_name='vmdefinition',
            old_name='default_user_sudo',
            new_name='student_user_sudo',
        ),
        migrations.RemoveField(
            model_name='vmdefinition',
            name='default_user',
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='default_user_password',
            field=models.CharField(blank=True, help_text='(Linux-only) Password default user (username is OS-dependant), leave blank to disable.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='student_user',
            field=models.BooleanField(default=True, help_text="(Linux-only) Create a user in the system based on student's username and a random password (will be provided to student).", verbose_name='Create system account for student'),
        ),
    ]
