# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0020_auto_20170504_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmdefinition',
            name='package_reboot_if_required',
            field=models.NullBooleanField(verbose_name='Perform reboot if required after package install/upgrade'),
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='package_update',
            field=models.NullBooleanField(verbose_name='Update package lists on boot'),
        ),
        migrations.AddField(
            model_name='vmdefinition',
            name='package_upgrade',
            field=models.NullBooleanField(verbose_name='Upgrade all packages on boot'),
        ),
    ]
