# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvcl', '0022_auto_20170504_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmdefinition',
            name='console_log',
            field=models.BooleanField(default=True, help_text='Disable when you want to conceal certain startup behavior. You always have access to console log.', verbose_name='Allow student access to console log'),
        ),
    ]
